MovieStoreApp.WebMVC/Models/ErrorViewModel.cs
namespace MovieStoreApp.WebMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieStoreApp.WebMVC/Models/GenderModel.cs
namespace MovieStoreApp.WebMVC.Models
{
    public class GenderModel
    {
        public int Id { get; set; }
        public string Gender { get; set; }
    }
}

MovieStoreApp.WebMVC/Models/MovieViewModel.cs
namespace MovieStoreApp.WebMVC.Models
{
    public class MovieViewModel
    {
       }
}

MovieStoreApp.WebMVC/Component/LatestMovieViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieStoreApp.Core.Contract.Service;
namespace MovieStoreApp.WebMVC.Component
{
    public class LatestMovieViewComponent:ViewComponent
    {
        IMovieServiceAsync movieService;
        public LatestMovieViewComponent(IMovieServiceAsync ser)
        {
            movieService = ser;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var result = await movieService.GetTop3LatestMoviesAsync();
            return View("latestmovie",result);
        }
    }
}

MovieStoreApp.WebMVC/Component/TopMovieViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieStoreApp.Core.Contract.Service;

namespace MovieStoreApp.WebMVC.Component
{
    public class TopMovieViewComponent:ViewComponent
    {
        IMovieServiceAsync movieService;
        public TopMovieViewComponent(IMovieServiceAsync ser)
        {
            movieService = ser;
        }
       
       
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var result = await movieService.GetTop10RevenueMoviesAsync();
            return View(result);
            
        }

        
    }
}

MovieStoreApp.WebMVC/Controllers/CastController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MovieStoreApp.Core.Contract.Service;
using MovieStoreApp.Core.Models;
using MovieStoreApp.WebMVC.Models;

namespace MovieStoreApp.WebMVC.Controllers
{
    //[Route("cast")]
    public class CastController : Controller
    {
       private readonly ICastServiceAsync castServiceAsync;

        IMovieCastService movieCastService;

        public CastController(ICastServiceAsync _castServiceAsync, IMovieCastService service)
        {
            castServiceAsync = _castServiceAsync;
            movieCastService = service;
        }
       // [Route("list")]
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Detail(int castId)
        {
            var result = await castServiceAsync.GetCastAsync(castId);
            result.MovieCasts = await movieCastService.GetAllByCastId(castId);
            return View(result);
        }




        //[Route("add")]
        public IActionResult Create()
        {
            ViewBag.Gender= new SelectList(GetGenders(),"Id","Gender");
            return View();
        }

        public IActionResult Delete()
        {
            ViewBag.Gender = new SelectList(GetGenders(), "Id", "Gender");
            return View();
        }

        public IActionResult Update()
        {
            ViewBag.Gender = new SelectList(GetGenders(), "Id", "Gender");
            return View();
        }




        [NonAction]
        private IEnumerable<GenderModel> GetGenders()
        {
          return  new List<GenderModel>() {
             new GenderModel(){ Id=1, Gender="Male"},

             new GenderModel(){ Id=2, Gender="Female"}
            };
        }

        [HttpPost]
        public IActionResult Create(CastModel model)
       {

            ViewBag.Gender = new SelectList(GetGenders(), "Id", "Gender");
            if (model.ProfilePath != null)
            {
                castServiceAsync.AddCastAsync(model);
                return RedirectToAction("Index");
            }
            //call the service to insert the data

            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(CastModel model)
        {

            ViewBag.Gender = new SelectList(GetGenders(), "Id", "Gender");
            if (model.ProfilePath != null)
            {
                castServiceAsync.DeleteCastAsync(model.Id);
                return RedirectToAction("Index");
            }
            //call the service to insert the data

            return View(model);
        }

        [HttpPost]
        public IActionResult Update(CastModel model)
        {

            ViewBag.Gender = new SelectList(GetGenders(), "Id", "Gender");
            if (model.ProfilePath != null)
            {
                castServiceAsync.UpdateCastAsync(model);
                return RedirectToAction("Index");
            }
            //call the service to insert the data

            return View(model);
        }
    }
}

MovieStoreApp.WebMVC/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;
using MovieStoreApp.Core.Contract.Service;
using MovieStoreApp.WebMVC.Models;

namespace MovieStoreApp.WebMVC.Controllers
{
    public class GenreController : Controller
    {
        IGenreServiceAsync Genre;
        public GenreController(IGenreServiceAsync _G)
        {
            Genre = _G;
        }

        public async Task<IActionResult> Index(int genreId)
        {
            ViewBag.Title = await Genre.GetGenreName(genreId);
            var result= await Genre.GetAllByGenre(genreId);
            return View(result);
        }
    }
}

MovieStoreApp.WebMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MovieStoreApp.WebMVC.Models;
using System.Diagnostics;

namespace MovieStoreApp.WebMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieStoreApp.WebMVC/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace MovieStoreApp.WebMVC.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MovieStoreApp.WebMVC/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using MovieStoreApp.Core.Contract.Service;
using MovieStoreApp.WebMVC.Models;

namespace MovieStoreApp.WebMVC.Controllers
{
    public class MovieController : Controller
    {
        IMovieServiceAsync movieService;
        IMovieCastService movieCastService;
        public MovieController(IMovieServiceAsync ser, IMovieCastService service)
        {
            movieService = ser;
            movieCastService = service;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "All Movies";

           // var result =await movieService.GetTop10RevenueMoviesAsync();

            return View();
        }

        public async Task<IActionResult> Detail(int movieId)
        { 
            var result =await movieService.GetByIdAsync(movieId);
            result.MovieCasts= await movieCastService.GetAllByMovieId(movieId);
            return View(result);
        }

    }
}

MovieStoreApp.WebMVC/Views/Cast/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model CastModel
<h3 class="display-3">Add Cast</h3><hr/>
<form method="post" asp-controller="Cast" asp-action="Create">
<div class="container">
    <div class="my-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control"/>
        <span asp-validation-for="Name" class="text-danger" >
            
        </span>
    </div>
    <div class="my-3">
        <label asp-for="Gender"></label>
        <select asp-for="Gender" class="form-control" asp-items="ViewBag.Gender">
           <option>Select Gender</option>
        </select>
        <span asp-validation-for="Gender" class="text-danger" >
            
        </span>
    </div>
    <div class="my-3">
        <label asp-for="TmdbUrl"></label>
        <input asp-for="TmdbUrl"class="form-control" />
        <span asp-validation-for="TmdbUrl" class="text-danger" >
            
        </span>
    </div>
    <div class="my-3">
        <label asp-for="ProfilePath"></label>
        <input asp-for="ProfilePath" class="form-control"/>
        <span asp-validation-for="ProfilePath" class="text-danger" >
            
        </span>
    </div>
    <input type="submit" value="Add Cast" class="btn btn-primary"/>
</div>
</form>

MovieStoreApp.WebMVC/Views/Cast/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model CastModel
<h3 class="display-3">Delete Cast</h3><hr/>
<form method="post" asp-controller="Cast" asp-action="Delete">
<div class="container">
    <div class="my-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control"/>
        <span asp-validation-for="Name" class="text-danger" >
            
        </span>
    </div>
    <div class="my-3">
        <label asp-for="Gender"></label>
        <select asp-for="Gender" class="form-control" asp-items="ViewBag.Gender">
           <option>Select Gender</option>
        </select>
        <span asp-validation-for="Gender" class="text-danger" >
            
        </span>
    </div>
    <div class="my-3">
        <label asp-for="TmdbUrl"></label>
        <input asp-for="TmdbUrl"class="form-control" />
        <span asp-validation-for="TmdbUrl" class="text-danger" >
            
        </span>
    </div>
    <div class="my-3">
        <label asp-for="ProfilePath"></label>
        <input asp-for="ProfilePath" class="form-control"/>
        <span asp-validation-for="ProfilePath" class="text-danger" >
            
        </span>
    </div>
    <input type="submit" value="Delete Cast" class="btn btn-primary"/>
</div>
</form>

MovieStoreApp.WebMVC/Views/Cast/Detail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model CastModel

<div class="container">
    <h3 class="display-4">@Model.Name</h3> <hr />
    <div class="row">
        <div class="col-4">
            <img src="@Model.ProfilePath" />
        </div>
        <div class="col-8">
            <ul class="list-group">
                <li class="list-group-item">Name - @Model.Name</li>

                @{if (@Model.Gender == 1)
                {
                    <li class="list-group-item">Gender - Female</li>
                }
                else if (@Model.Gender==2){
                    <li class="list-group-item">Gender - Male</li>
                }
                else{
                    <li class="list-group-item">Gender - Other</li>
                }}

                <li class="list-group-item">Tmdb URL - @Model.TmdbUrl</li>
            </ul>

            <hr/>

            <div class="row">
                @foreach (var mcast in @Model.MovieCasts)
                {
                    <partial name="_MovieCard" model="@mcast.Movie"></partial>
                }
       </div>
    </div>
</div>

MovieStoreApp.WebMVC/Views/Cast/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h3 class="display-4" >Cast Index</h3>

MovieStoreApp.WebMVC/Views/Cast/Update.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model CastModel
<h3 class="display-3">Update Cast</h3><hr/>
<form method="post" asp-controller="Cast" asp-action="Update">
<div class="container">
    <div class="my-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control"/>
        <span asp-validation-for="Name" class="text-danger" >
            
        </span>
    </div>
    <div class="my-3">
        <label asp-for="Gender"></label>
        <select asp-for="Gender" class="form-control" asp-items="ViewBag.Gender">
           <option>Select Gender</option>
        </select>
        <span asp-validation-for="Gender" class="text-danger" >
            
        </span>
    </div>
    <div class="my-3">
        <label asp-for="TmdbUrl"></label>
        <input asp-for="TmdbUrl"class="form-control" />
        <span asp-validation-for="TmdbUrl" class="text-danger" >
            
        </span>
    </div>
    <div class="my-3">
        <label asp-for="ProfilePath"></label>
        <input asp-for="ProfilePath" class="form-control"/>
        <span asp-validation-for="ProfilePath" class="text-danger" >
            
        </span>
    </div>
    <input type="submit" value="Update Cast" class="btn btn-primary"/>
</div>
</form>

MovieStoreApp.WebMVC/Views/Genre/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model IEnumerable<MovieResponseModel>;

<div class="row">
    <div class="col-9">
        <h1>
            @ViewBag.Title
        </h1>
    </div>
</div>
<hr/>
<h2>Movies</h2>
<div class="row">
    @foreach (var mcast in @Model)
    {
        <partial name="_MovieCard" model="@mcast"></partial>
     }
</div>

MovieStoreApp.WebMVC/Views/Home/Index.cshtml
@{
    
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MovieStoreApp.WebMVC/Views/Login/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}

<h1>This is login page</h1>
Razor view 
its extensiton is

cshtml
cs + html


Razor View Engine:- it is a piece of code which will convert the C# code of the razor
view to an html code.

@{
    int a = 20;
    int b = 30;
    int c = a + b;
    <h3>Sum = @c </h3>
    <table border="1">
    @for (int i = 0; i < 10; i++)
    {
        <tr>
        <td  >@i</td>
        </tr>
    }
    </table>

}


Layout
header--- menu, logo, login/signup

Content:- it will be keep changing

footer-- rights, social media icon

Shared views

section RenderBody()

MovieStoreApp.WebMVC/Views/Movie/Detail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model MovieResponseModel
<div class="container">
    <h3 class="display-4">@Model.Title Detail</h3> <hr />
    <div class="row">
        <div class="col-4">
            <img src="@Model.PosterUrl" />
        </div>
        <div class="col-8">
            <ul class="list-group">
                <li class="list-group-item">Title - @Model.Title</li>
                <li class="list-group-item">Tagline - @Model.Tagline</li>
                <li class="list-group-item">Runtime - @Model.Runtime | Budget - @Model.Budget</li>
                <li class="list-group-item">Description - @Model.Overview</li>
                <li class="list-group-item">Language - @Model.OriginalLanguage | Release On : @Model.ReleaseDate.ToShortDateString() </li>
            </ul>
            <hr/>

            <div class="row">
                @foreach (var mcast in @Model.MovieCasts)
                {
                    <partial name="_CastCard" model="@mcast.Cast"></partial>

                }
            </div>
            <hr/>
                <a target="_blank" asp-controller="genre" asp-action="index" asp-route-genreId="@((@Model.Runtime)%20+1)" class="btn btn-primary">Find Similar Movies</a>
            
        </div>

        
    </div>
</div>

MovieStoreApp.WebMVC/Views/Movie/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<MovieResponseModel>;
<div class="row">
    <div class="col-9">
        <h1>
            @ViewBag.Title
        </h1>
    </div>
@*    <div class="col-3">
        <a asp-controller="Movie" asp-action ="Create">Add New Movie</a>
    </div>*@
</div>
<hr/>
<h2>Top Revenue Movies</h2>
@await Component.InvokeAsync("TopMovie")
<hr/>
<h2>Latest movies</h2>
@await Component.InvokeAsync("LatestMovie")
 

MovieStoreApp.WebMVC/Views/Shared/Components/LatestMovie/latestmovie.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<MovieResponseModel>

<div class="row">
    @foreach (var m in Model)
    {
       <partial name="_MovieCard" model="@m"></partial>
    }
</div>

MovieStoreApp.WebMVC/Views/Shared/Components/TopMovie/default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<MovieResponseModel>

<div class="row">
    @foreach (var m in Model)
    {
       <partial name="_MovieCard" model="@m"></partial>
    }
</div>

MovieStoreApp.WebMVC/Views/Shared/_CastCard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model CastModel;

<div class="col-6 mb-4">
  <div class="card" style="width: 18rem;">
  <img src="@Model.ProfilePath" width="1px" height="300px" class="card-img-top" alt="...">
  <div class="card-body">
  <h5 class="card-title">@Model.Name</h5>

  @{if (@Model.Gender == 1)
  {
      <p class="card-text">Female</p>
  }
  else if (@Model.Gender==2){
      <p class="card-text">Male</p>
  }
  else{
      <p class="card-text">Other</p>
  }}

  <a target="_blank" asp-controller="cast" asp-action="detail" asp-route-castId="@Model.Id" class="btn btn-primary">Show Details</a>

  </div>
  </div>
  </div>
  <br />

MovieStoreApp.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My MovieStore App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieStoreApp.WebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movie" asp-action="Index">Movie Database</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">All Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
          @RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MovieStoreApp.WebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
        
</body>
</html>

MovieStoreApp.WebMVC/Views/Shared/_MovieCard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model MovieResponseModel;

 <div class="col-4 mb-4">
            <div class="card" style="width: 18rem;">
                <img src="@Model.PosterUrl" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@Model.Title</h5>
                    <p class="card-text">@Model.Overview</p>
                    <a target="_blank" asp-controller="movie" asp-action="detail" asp-route-movieId="@Model.Id" class="btn btn-primary">Show Details</a>
                </div>
            </div>
        </div>
        <br />